//! Shared protocol, data model and algorithms for the remote-compile fleet.
//!
//! Everything that must agree between `rc-agent`, `rc-server` and `rc-worker`
//! lives here: the gRPC wire types, the content-addressing rules, the task
//! fingerprint, build-profile resolution and the language adapters.

pub mod adapter;
pub mod ansi;
pub mod cas;
pub mod diag;
pub mod discover;
pub mod envdep;
pub mod fingerprint;
pub mod ids;
pub mod manifest;
pub mod model;
pub mod profile;
pub mod roots;
pub mod transport;

pub mod pb {
    // Generated by prost; its oneof variants legitimately differ in size.
    #![allow(clippy::large_enum_variant)]
    tonic::include_proto!("rc.v1");
}

pub use model::{ResultKind, TaskState, TaskType};

/// Version of the agent<->server<->worker contract. Bumped on breaking changes.
pub const PROTOCOL_VERSION: u32 = 1;

/// Worker capability: understands `Manifest.anchor_mount` and can therefore
/// rebuild a workspace holding more than one root.
///
/// A worker without it would extract the git baseline at the top of the
/// workspace instead of under the primary root's mount. Every baseline file
/// would then be a stray at the wrong path, get deleted, and be re-fetched from
/// a CAS that never held it — because baseline content is deliberately not
/// uploaded. The task would fail in a way that looks like CAS corruption, so
/// such a worker is excluded from multi-root tasks instead.
pub const CAP_MULTI_ROOT: &str = "multi-root";

/// Capabilities this build advertises.
pub const CAPABILITIES: &[&str] = &[CAP_MULTI_ROOT];

/// Directories never synced, regardless of adapter.
pub const ALWAYS_EXCLUDE: &[&str] = &[".git", "node_modules", ".direnv", ".venv"];

/// Default hard timeout for a single task, in seconds (§7.1).
pub const DEFAULT_TASK_TIMEOUT_SECS: u32 = 600;

/// Task-level result cache TTL (§5.1) — non-deterministic builds make an
/// unbounded cache unsafe.
pub const TASK_CACHE_TTL_SECS: i64 = 24 * 3600;

/// Pending tasks nobody ever collects are reaped after this (§5.3).
pub const PENDING_TTL_SECS: i64 = 30 * 60;

/// Wall-clock milliseconds since the unix epoch.
pub fn now_ms() -> i64 {
    use std::time::{SystemTime, UNIX_EPOCH};
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_millis() as i64)
        .unwrap_or(0)
}

/// Wall-clock seconds since the unix epoch.
pub fn now_secs() -> i64 {
    now_ms() / 1000
}
